

# Ledger
#no-ledger: true
genesis-url: http://test.bcovrin.vonx.io/genesis

# Wallet
auto-provision: true #It must be false in production
seed: pier0000000000000000000000000000
#wallet-allow-insecure-seed: true # Uncomment this if no seed is declared
wallet-type: askar-anoncreds
wallet-name: EndorserDBName
wallet-key: change-me-key
wallet-storage-type: postgres_storage
#wallet-storage-config: '{"url":"localhost:5432", "wallet_scheme": "DatabasePerWallet"}'
#wallet-storage-creds: '{"account":"acapy", "password":"acapy", "admin_account":"acapy", "admin_password":"acapy"}'

# Endorser
auto-endorse-transactions: true # Comment when using a controller 
endorser-protocol-role: endorser

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true
public-invites: true

# Protocol settings
monitor-ping: true
emit-new-didcomm-prefix: true
emit-new-didcomm-mime-type: true
#--preserve-exchange-records # For Issuer or a Endorser-Issuer

# Transport settings
label: Accréditeur
#image-url:
inbound-transport:
  - [http, 0.0.0.0, 3003]
  
outbound-transport: http
endpoint:
  - http://host.docker.internal:3003

#max-message-size:À déterminer
enable-undelivered-queue: true

# Admin-Swagger
admin: [0.0.0.0, 3004]
#admin-api-key: change-me-api-key
admin-insecure-mode: true


# Revocation
#tails-server-base-url:

# Logging settings
#log-level: info